### Registro de usuario
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "crojas",
  "password": "crojas"
}

### Login de usuario
POST http://localhost:9001/auth/login
Content-Type: application/json

{
  "username": "crojas",
  "password": "crojas"
}

# NOTA:
# Al hacer login, la respuesta debe contener el access_token (JWT) y el refresh_token.
# Copia el valor de "refresh_token" y "access_token" de la respuesta para usarlos en las siguientes peticiones.

### Refresh token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "username": "crojas",
  "refresh_token": "5dad3a4b-9427-4e5b-8817-ea9f144a1ba0"
}

### Validar token
GET http://localhost:8080/auth/validate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGgtc2VydmljZS5rdWFycXVzLmNvbSIsInN1YiI6ImNyb2phcyIsInVwbiI6ImNyb2phcyIsImdyb3VwcyI6W10sImlhdCI6MTc3NDg0MTMxNSwiZXhwIjoxNzc0ODQ0OTE1LCJqdGkiOiJjNmQ5MmJhYi1hZjgxLTRhN2UtYTJkNC1lMjdhMzJhNjk2ZjcifQ.TVoyXgIT8rYaNDKeNmurfgLiW83Y_PhYI8ICFxrsMuLr2n9vx6oLHXyGf1-jVg5CYDASbU4-WPeaTOj7LYeGM8d1YPps5cJbH64RBtIJcct6udshmV4iOk2a81nGdYUlB_s1cfDdH7FivZiWcEtSsxbW_rqcFTQITykNr98hd1x9M9OM8a_o35CSHQwfEjqkikQfORKA9g2IpyNO-UJ4VzE3_93g_Xwcswn04BLQnPRogptZ5_jo0Mw8cCQA2G_7EcU0IvGIlVo_9mvhy_WOHGevSGllFrZ39jvADuxJp0l9m0m979Wtdh50bBVJXJs2RvLalLMeaE8_3khj42yr_w


### Login de usuario por kong
POST http://localhost:8081/mcsv-login/auth/login
Content-Type: application/json

{
  "username": "crojas",
  "password": "crojas"
}