# Configuración de PostgreSQL

quarkus.hibernate-orm.database.start-offline=true
quarkus.hibernate-orm.database.version-check.enabled=false
quarkus.hibernate-orm.schema-management.strategy=none


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5444/db_auth
quarkus.hibernate-orm.database.default-schema=data
# quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Configuración de JWT
# mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
# quarkus.smallrye-jwt.sign.key-location=META-INF/resources/privateKey.pem

# Configuración de JWT con archivos en el mismo directorio
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem

mp.jwt.verify.issuer=https://auth-service.kuarqus.com

# Rutas públicas (necesarias para poder autenticarse)
quarkus.http.auth.permission.public.paths=/auth/login,/auth/register,/auth/refresh
quarkus.http.auth.permission.public.policy=permit

# Todo lo demás requiere JWT válido
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# JWT Token Configuration
jwt.issuer=https://auth-service.kuarqus.com
jwt.duration=3600
jwt.refresh.duration=86400


# HTTP Configuration
quarkus.http.port=9001
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# quarkus.smallrye-jwt.token.header=Authorization
# quarkus.smallrye-jwt.token.cookie=
# quarkus.smallrye-jwt.auth-mechanism=MP-JWT
# quarkus.smallrye-jwt.expiration=3600

quarkus.log.console.enable=true
quarkus.log.console.color=true
quarkus.log.console.level=INFO
quarkus.log.level=INFO

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n


quarkus.profile=dev

